# Generated by Django 5.2 on 2026-05-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_budget_remove_trip_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
    ]
