# Generated by Django 5.2 on 2026-05-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_expense_options'),
        ('trips', '0003_destination'),
    ]

    operations = [
    ]
