# Generated by Django 5.2 on 2026-05-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_merge_0003_alter_expense_options_0003_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
