# Generated by Django 5.2 on 2026-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(help_text='e.g., Western Europe, Southeast Asia', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(help_text='Brief, engaging description of the destination')),
                ('image_url', models.URLField(blank=True, help_text='Hero image for the destination card', null=True)),
                ('budget_level', models.CharField(choices=[('budget', 'Budget-Friendly'), ('moderate', 'Moderate'), ('luxury', 'Luxury')], default='moderate', max_length=20)),
                ('avg_cost_per_day', models.DecimalField(decimal_places=2, help_text='Average daily cost in USD', max_digits=8)),
                ('categories', models.CharField(help_text='Comma-separated: beach, culture, adventure, food, history, nightlife, nature, shopping', max_length=255)),
                ('best_months', models.CharField(help_text="Best months to visit (e.g., 'Apr-Jun, Sep-Oct')", max_length=100)),
                ('popularity_score', models.IntegerField(default=50, help_text='1-100 ranking for featured/trending destinations')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-popularity_score', 'city'],
                'indexes': [models.Index(fields=['city', 'country'], name='destination_city_64e115_idx'), models.Index(fields=['budget_level'], name='destination_budget__ae1294_idx'), models.Index(fields=['popularity_score'], name='destination_popular_783da0_idx')],
            },
        ),
    ]
